### ISSUE TITLE
i2C触控板型号

### ISSUE THREAD

**Issue by EmiliaZhang** [balopez83/One_Mix_Yoga_4_Hackintosh#24]
求教i2C触控板

**Comment by balopez83** [comment]
Hi, I am unsure what you are asking for assistance with? Currently the trackpad is supported but is not reliable. You can view the [https://github.com/balopez83/One_Mix_Yoga_4_Hackintosh/blob/main/3-quirks%26fixes.md](url) instructions for some ways to improve the trackpad. 

Once Graphics Acceleration is achieved the trackpad is expected to improve.

**Comment by balopez83** [comment]
VoodooI2C kext requires a patch for the Tiger Lake chipsets. Additionally, the device requires an SSDT patch to correctly Pin the trackpad and touchscreen to enable both. You can use our modified voodooi2c kexts to see if you can drive your computer though no guarantees since our devices may be different.
