### ISSUE TITLE
Tiger Lake-LP Smart Sound Technology Audio Controller

### ISSUE THREAD

**Issue by EmiliaZhang** [balopez83/One_Mix_Yoga_4_Hackintosh#25]

**Comment by balopez83** [comment]
This requires a modified ALC kext that has the added Tiger Lake chipset identifier. The default kext will not work as Tiger Lake is not yet considered supported. Once the modified kext was installed we simply needed to test the layouts for this audio device which resulted in a mostly working audio device. You can try using our custom kexts and see if it will drive your computer though no guarantees it will work since you seem to have a different computer.
