### ISSUE TITLE
AppleALC.kext need to change MaxKernel run Big Sur

### ISSUE THREAD

**Issue by EmiliaZhang** [balopez83/One_Mix_Yoga_4_Hackintosh#26]
Otherwise the device cannot be found on Big Sur ？

**Comment by balopez83** [comment]
Our version of AppleALC.kext does work in Big Sur. There is no kernel min/max version restrictions. You must use our custom AppleALC if you want it to work on a Tiger Lake chipset. The current non-custom release does not natively support the Tiger Lake chipset yet which is why we had to modify it. 

If you want sound to work you will need to copy AppleALC-custom.kext from our repo and install it in your EFI in order to get it to work. You must also figure out what codec is right for your system in order for it to fully load.
